coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: "condensed_header, diff"
  behavior: default

ignore:
  - "tests/**/*"
  - "**/*_test.rs"
  - "src/main.rs"              # Entry point - integration tested only
