coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: "condensed_header, diff"
  behavior: default

ignore:
  - "tests/**/*"
  - "**/*_test.rs"
  - "src/main.rs"              # Entry point - integration tested
  - "src/permissions.rs"        # Requires macOS permissions
  - "src/telemetry.rs"          # Requires tracing/filesystem init
  - "src/tray.rs"               # Requires macOS GUI system
  - "src/input/cgevent.rs"      # Requires accessibility permissions
  - "src/audio/capture.rs"      # Requires audio hardware
  - "src/transcription/engine.rs"  # Requires Whisper model files
