name: Shellcheck

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    paths:
      - 'scripts/**/*.sh'
      - '.github/workflows/shellcheck.yml'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3
        with:
          version: 2025.11.11
      - name: Run shellcheck
        run: mise exec -- shellcheck scripts/*.sh
